### ISSUE TITLE
Main branch is broken

### ISSUE THREAD

**Issue by robert14-els** [PaloAltoNetworks/prisma-cloud-scan#15]
## Describe the bug

The main branch action appears to be broken.  Assuming it was this PR https://github.com/PaloAltoNetworks/prisma-cloud-scan/pull/14 as running off that branch also seems broken.

```
Run PaloAltoNetworks/prisma-cloud-scan@main
  with:
    pcc_console_url: ***
    pcc_user: ***
    pcc_pass: ***
    image_name: alpine
    results_file: pcc_scan_results.json
    sarif_file: pcc_scan_results.sarif.json
  env:
    prisma_token: ***
internal/modules/cjs/loader.js:800
    throw err;
    ^

Error: Cannot find module 'node-fetch'
Require stack:
- /runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:797:15)
    at Function.Module._load (internal/modules/cjs/loader.js:690:27)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.585 (/runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js:4966:33)
    at __nccwpck_require__ (/runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js:5097:43)
    at /runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js:5115:15
    at /runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js:5388:3
    at Object.<anonymous> (/runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js:5391:12)
    at Module._compile (internal/modules/cjs/loader.js:959:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/runner/_work/_actions/PaloAltoNetworks/prisma-cloud-scan/main/dist/index.js'
  ]
}
```

## Expected behavior

Up to and including sha b59f37f95d1b488ff66259be02b2f16f1fe4fa2c main branch has been scanning fine.

## Current behavior

Error see above

## Steps to reproduce

1. Run scan using the main branch
2. See error
3.
4.

## Your Environment

- Version used: main
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): Actions Self hosted runner
- Operating System and version (desktop or mobile): linux runner
- Link to your project: -

**Comment by wfg** [comment]
@robert14-els yes, sorry about that. Try again--https://github.com/PaloAltoNetworks/prisma-cloud-scan/commit/8f766fb9862d9c01fc273ccd27937d7a68986b11 should have fixed it. I ran a test successfully here: https://github.com/wfg/scan-action-test/runs/4898773202

**Comment by robert14-els** [comment]
Thanks looks to be good again :) 
I have a couple of actions runners running in Kubernetes building container with BuildX which we have never been able to scan with before as there is no docker sock and containerized would just scan the runner container.  So I will give this new option a go too

**Comment by wfg** [comment]
Awesome! I'll go ahead and close this then.

**Comment by apr-1985** [comment]
I have opened https://github.com/PaloAltoNetworks/prisma-cloud-scan/pull/16 (under my other account)

**Comment by nwhobart** [comment]
@robert14-els how did you get this to run on a `self-hosted` runner? I keep running into: 

`API error (400): Client sent an HTTP request to an HTTPS server.`

**Comment by apr-1985** [comment]
What does the underlying twistcli command look like when you run the action. 
if you could keep in the http(s) protocol on the address would be helpful. 

E.g. mine looked like

```
/opt/hostedtoolcache/twistcli/20.12.535/x64/twistcli images scan --address *** --user *** -*** --output-file pcc_scan_results.json --details --docker-address tcp://localhost:2376 --docker-tlscacert /certs/client/ca.pem --docker-tlscert /certs/client/cert.pem --docker-tlskey /certs/client/key.pem java-demo-app:latest
```

**Comment by nwhobart** [comment]
hi @apr-1985 thanks for the response. looks similar to this: 

```
Run PaloAltoNetworks/prisma-cloud-scan@v1.5
  with:
    pcc_console_url: https://us-west1.cloud.twistlock.com/us-4-161027597
    pcc_user: ***
    pcc_pass: ***
    image_name: hobatest:7170b1071313a3827a104c01c47f76d5cb10fad8
    results_file: pcc_scan_results.json
    sarif_file: pcc_scan_results.sarif.json
  env:
    IMAGE_NAME: hobatest:7170b1071313a3827a104c01c47f76d5cb10fad8
    TWISTLOCK_CONSOLE_URL: https://us-west1.cloud.twistlock.com/us-4-blah
/usr/bin/chmod a+x /runner/_work/_temp/ef281b26-c04d-4945-b9e2-8db937b1e71a
/opt/hostedtoolcache/twistcli/30.03.122/x64/twistcli images scan --address https://us-west1.cloud.twistlock.com/us-4-blah --user *** -*** --output-file pcc_scan_results.json --details --docker-address tcp://localhost:2376 test:7170b1071313a3827a104c01c47f76d5cb10fad8
API error (400): Client sent an HTTP request to an HTTPS server.
```

I manually tried using the `2376` port as that's what others suggested. 

My base image for this whole thing is: 

`summerwind/actions-runner:ubuntu-22.04`

interestingly i started experimenting and: 

`summerwind/actions-runner-dind:ubuntu-22.04`

works as expected however I don't know what downstream impact that change of base image could have on other workflows in my org so i'm hesitant to up and change base images.

**Comment by nwhobart** [comment]
update: after i specified the `certs` paths it's working! :) 

```
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: ${{ env.TWISTLOCK_CONSOLE_URL }}
          pcc_user: ${{ secrets.TWISTLOCK_USERNAME }}
          pcc_pass: ${{ secrets.TWISTLOCK_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          docker_tlscacert: /certs/client/ca.pem
          docker_tlscert: /certs/client/cert.pem
          docker_tlskey: /certs/client/key.pem
```
