### ISSUE TITLE
Sarif file failing to upload due to duplicate CVE warning

### ISSUE THREAD

**Issue by morlando016** [PaloAltoNetworks/prisma-cloud-scan#26]
## Describe the bug
This week our CI builds have broken due to duplicate CVE warnings appearing in the sarif report from the `prisma-cloud-scan` action

## Expected behavior
Before this week builds were working fine and were able to upload the sarif file to github without issue.

## Current behavior
Currently, there is a duplicate CVE ([CVE-2022-45061](https://nvd.nist.gov/vuln/detail/CVE-2022-45061)) appearing in our sarif report. The upload to github fails as it does not expect a duplicate in the results. We are scanning a dotnet lambda docker image. The exact image is `public.ecr.aws/lambda/dotnet:6.2023.02.03.12`.

## Possible solution
Option to ignore duplicate issues found. Could also be solved by having the upload action ignore duplicates or AWS updating their images.

## Steps to reproduce

1. Create a dockerfile using `public.ecr.aws/lambda/dotnet:6.2023.02.03.12` as the base image
`FROM public.ecr.aws/lambda/dotnet:6.2023.02.03.12`

2. Scan the dockerfile using the `PaloAltoNetworks/prisma-cloud-scan@v1` action in github actions
```
- name: Prisma Cloud Image Scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1
        with:
          pcc_console_url: ${{ secrets.PRISMA_BASE_URL }}
          pcc_user: ${{ secrets.PRISMA_ACCESS_KEY_ID }}
          pcc_pass: ${{ secrets.PRISMA_SECRET_KEY }}
          image_name: ${{ env.IMAGE_NAME }}:${{ steps.gitversion.outputs.nuGetVersionV2 }}
```

3. Try to upload the SARIF file using `github/codeql-action/upload-sarif@v2` in github actions
```
- name: Upload SARIF file
        if: always()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.scan.outputs.sarif_file }}
```

4. Error should appear `Error details: instance.runs[0].tool.driver.rules contains duplicate item`

## Screenshots
![image](https://user-images.githubusercontent.com/14007828/217094064-9fe0e3bb-a968-4321-925e-0e5bb2159567.png)
![image](https://user-images.githubusercontent.com/14007828/217094161-0fbc641e-c25d-488f-94a3-8186c3df5557.png)

## Context
This has broken CI builds as the sarif file with the duplicates cannot be uploaded

## Your Environment

- Version used: PaloAltoNetworks/prisma-cloud-scan@v1
- Environment name and version: Github actions running on `Ubuntu-Latest`
