### ISSUE TITLE
Unable to run on self-hosted runners

### ISSUE THREAD

**Issue by nwhobart** [PaloAltoNetworks/prisma-cloud-scan#37]
## Describe the bug

When running this action using a `self-hosted` runner, I am presented with the following error on every run: 

`API error (400): Client sent an HTTP request to an HTTPS server.`

## Expected behavior

`self-hosted` runners work just as `ubuntu-latest` works

## Current behavior

see screenshot. 

## Steps to reproduce

```
on: [ push, workflow_dispatch ]

env:
  IMAGE_NAME: test:${{ github.sha }}
  TWISTLOCK_CONSOLE_URL: https://us-west1.cloud.twistlock.com/xxxxxxxx

jobs:
  build-and-scan:
    name: Build and scan image
    runs-on: self-hosted

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Build the image
        run: docker build -t $IMAGE_NAME .

      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: ${{ env.TWISTLOCK_CONSOLE_URL }}
          pcc_user: ${{ secrets.TWISTLOCK_USERNAME }}
          pcc_pass: ${{ secrets.TWISTLOCK_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
```

## Screenshots

![prisma](https://github.com/PaloAltoNetworks/prisma-cloud-scan/assets/4466324/1de1a627-3527-4c08-a67e-d4e865934238)

## Context

We are unable to run the scanner using our self-hosted runners

## Your Environment

- Version used:
- Environment name and version (e.g. Chrome 59, node.js 5.4, python 3.7.3): `self-hosted` runner based on Ubuntu 22.04
- Operating System and version (desktop or mobile):
- Link to your project:

**Comment by nwhobart** [comment]
If anyone else runs into this, make sure to specify the certs paths: 

```
      - name: Prisma Cloud image scan
        id: scan
        uses: PaloAltoNetworks/prisma-cloud-scan@v1.5
        with:
          pcc_console_url: ${{ env.TWISTLOCK_CONSOLE_URL }}
          pcc_user: ${{ secrets.TWISTLOCK_USERNAME }}
          pcc_pass: ${{ secrets.TWISTLOCK_PASSWORD }}
          image_name: ${{ env.IMAGE_NAME }}
          docker_tlscacert: /certs/client/ca.pem
          docker_tlscert: /certs/client/cert.pem
          docker_tlskey: /certs/client/key.pem
```
